In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import os
folder_path='/content/drive/MyDrive/תרגיל 6'
os.chdir(folder_path)

In [63]:
import pandas as pd
import numpy as np

**שאלה 1**

In [60]:
def ReadData (Str,Tpl):
  if isinstance(Str,str) != True:
    return None

  Excel = pd.read_excel(Str)
  FrameExcel = pd.DataFrame(data=Excel, columns=Tpl)
  Mat = FrameExcel.to_numpy() 

  return Mat

In [61]:
data2 = ReadData('data_2.xlsx',('a','b','e'))
print('data2:\n{}\n'.format(data2))

data2:
[[ 0 -2 13]
 [ 0  0 11]
 [-1 -2 15]
 [-1 -1  8]
 [-1 -1  5]
 [-1  1  9]
 [ 0 -1  7]
 [ 1 -1  3]
 [-1 -1  8]
 [ 1  0  5]
 [ 1  1 13]
 [ 1  0  1]
 [ 0  0 10]
 [-2  1  7]
 [ 1  0  8]]



In [62]:
data1 = ReadData('data_1.xlsx',('X','Z'))
print('data1[:10]:\n{}\n'.format(data1[:10]))

data1[:10]:
[[ 0.49132356 -1.41771793]
 [-0.03896942  2.44772496]
 [-1.39934501 -1.61542558]
 [-1.21776548  0.10482324]
 [-0.69810261 -0.37895783]
 [-0.88780233  4.82330584]
 [ 0.17884919  0.46557026]
 [ 0.61669139  1.93336617]
 [-0.55889258  0.85962682]
 [ 0.84028708  2.97607116]]



In [12]:
data2 = 'data_2.xlsx'
DR = pd.read_excel(data2)
print(DR)

    b   e  a  d  c
0  -2  13  0 -1  0
1   0  11  0  2  2
2  -2  15 -1 -2  0
3  -1   8 -1  0  1
4  -1   5 -1  0  1
5   1   9 -1  5  2
6  -1   7  0  0 -1
7  -1   3  1  2  1
8  -1   8 -1  1 -1
9   0   5  1  3 -1
10  1  13  1  4 -1
11  0   1  1  3  1
12  0  10  0  4  1
13  1   7 -2  5 -2
14  0   8  1  4 -1


In [11]:
data1 = 'data_1.xlsx'
DR = pd.read_excel(data1)
print(DR)

           Z         W         X          t         Y
0  -1.417718 -0.367960  0.491324   0.000000 -2.177237
1   2.447725  1.666527 -0.038969   0.151515 -0.425750
2  -1.615426 -0.323282 -1.399345   0.303030 -1.972809
3   0.104823  1.251018 -1.217765   0.454545 -0.930761
4  -0.378958  0.653776 -0.698103   0.606061 -1.493063
..       ...       ...       ...        ...       ...
95  0.255290 -0.342936 -0.285291  14.393939 -1.295301
96  2.441828  0.658673 -0.421321  14.545455 -0.485669
97 -0.099058 -1.913569 -1.003555  14.696970 -1.422098
98 -1.175327 -0.532078  0.581675  14.848485 -1.715053
99  3.712619  1.016807 -0.420889  15.000000  0.719369

[100 rows x 5 columns]


**שאלה 2**

In [64]:
def PearsonCorrelation (X,Y):
  R=(np.sum((X-np.mean(X))*(Y-np.mean(Y))))/(np.sqrt(np.sum((X-np.mean(X))**2)*np.sum((Y-np.mean(Y))**2)))
  return R

In [65]:
X = np.array([9,7,5,3,1])
Y = np.array([10,6,1,5,3])
R1= PearsonCorrelation(X ,Y)
print('R1: {}\n'.format(R1))

R1: 0.6993786061802354



In [66]:
X = np.array([1,0,1])
Y = np.array([0,2,1])
R2= PearsonCorrelation(X ,Y)
print('R2: {}\n'.format(R2))

R2: -0.8660254037844385



**שאלה 3**

In [ ]:
import matplotlib.pyplot as plt

In [93]:
def PlotMyData (Mat,List_num,List_names):
  NumOfWin = range(len(List_names))
  #if NumOfWin in range(Len):
  a = int(len(List_num[NumOfWin][0]))
  b = int(len(List_num[NumOfWin][1]))
  X = Mat [:, a]
  Y = Mat [:, b]
  R= PearsonCorrelation(X,Y)

  sub1 = List_names [NumOfWin][0]
  sub2 = List_names [NumOfWin][1]

  plt.figure()
  plt.subplot(len(List_names),1, NumOfWin+1)
  plt.title('{}: R{}'.format(sub1,sub2,R))
  plt.plot(X)
  plt.plot(Y)
  plt.legend(('{}'.format(sub1),'{}'.format(sub2)))
  plt.show()

In [91]:
data = ReadData('data_1.xlsx',('X','Y','Z'))
PlotMyData(data, ['01','12','02'],['XY','YZ','XZ'])

TypeError: ignored